---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cgi-prod
resources:
  - ../../base
  - hpa-api.yaml
  - virtual-service-cgi-prod.yaml
  - istio-gateway.yaml
  - secrets-cgi-prod.yaml
images:
  - name: app
    newTag: "5ee109b"
    newName: 528757797143.dkr.ecr.us-east-1.amazonaws.com/canine-glucose-ecr
patches:
  - path: deployment-cgi-app-prod.yaml
    target:
      kind: Deployment
      name: cgi-deployment
