# This should be replaced with a secrets manager as soon as possible, but for a proof of concept this will have to do.
# To Use: Rename this file to 'secrets-cgi-prod.yaml'

apiVersion: v1
kind: Secret
metadata:
  name: twilio-secrets
type: Opaque
stringData:
  TWILIO_API_KEY: "SKxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  TWILIO_API_SECRET: "your-secret-here"
  OWNER_PHONE: "call-this-number"
  CALLER_PHONE: "from-this-number"