---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secrets-cgi-dev.yaml

patches:
  - path: service-cgi-app-dev.yaml
    target:
      kind: Service
      name: cgi-service
  - path: deployment-cgi-app-dev.yaml
    target: 
      kind: Deployment
      name: cgi-deployment