---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cgi-local
resources:
  - deployment-cgi-app.yaml
  - deployment-redis.yaml
  - service-cgi-app.yaml
  - service-redis.yaml
configMapGenerator:
  - name: redis-configmap
    files:
      - redis-config/redis.conf
      - redis-config/redis-full.conf
generatorOptions:
  disableNameSuffixHash: true